Refactor CI workflows

diff --git a/.github/workflows/cppcmake-ubuntu.yml b/.github/workflows/cppcmake-ubuntu.yml
--- a/.github/workflows/cppcmake-ubuntu.yml
+++ b/.github/workflows/cppcmake-ubuntu.yml
@@ -2,7 +2,7 @@
 # If built on the latest OS, it may not run on previous OS versions.
 # Related: https://docs.appimage.org/reference/best-practices.html#binaries-compiled-on-old-enough-base-system
 
-name: Build - AppImage
+name: Build (Ubuntu)
 
 on:
   workflow_call:
@@ -10,54 +10,66 @@ on:
       NIGHTLY:
         default: false
         type: boolean
+  workflow_dispatch:
 
 jobs:
   build:
-    name: ${{ matrix.os }} - SQLCipher ${{ matrix.sqlcipher }}
+    name: ${{ matrix.os }} (${{ matrix.bundle }})
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
       matrix:
+        bundle: [SQLCipher, SQLite]
         os: [ubuntu-20.04]
-        sqlcipher: ["0", "1"]
     steps:
       - name: Checkout
         uses: actions/checkout@v4
 
-      - name: Install dependencies
-        run: |
-          sudo apt update
-          sudo apt install libqcustomplot-dev libqscintilla2-qt5-dev libqt5svg5 qttools5-dev
+      - name: Install and cache dependencies
+        uses: awalsh128/cache-apt-pkgs-action@v1.4.2
+        with:
+          packages: libqcustomplot-dev libqscintilla2-qt5-dev libqt5svg5 ninja-build qttools5-dev
 
-      - if: matrix.sqlcipher == 0
+      - if: matrix.bundle == 'SQLCipher'
+        name: Build SQLCipher
+        run: |
+          git clone https://github.com/sqlcipher/sqlcipher && cd sqlcipher && git checkout $(git describe --tags --abbrev=0)
+          ./configure --enable-tempstore=yes --with-crypto-lib=openssl --enable-load-extension --disable-tcl CFLAGS="-DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_SNAPSHOT=1 -DSQLITE_ENABLE_STAT4 -DSQLITE_HAS_CODEC -DSQLITE_SOUNDEX"
+          make -j2 && sudo make install -j2
+
+      - if: matrix.bundle == 'SQLite'
         name: Build SQLite
         run: |
           TARBALL=$(curl -s https://sqlite.org/download.html | awk '/<!--/,/-->/ {print}' | grep 'sqlite-autoconf' | cut -d ',' -f 3)
           SHA3=$(curl -s https://sqlite.org/download.html | awk '/<!--/,/-->/ {print}' | grep 'sqlite-autoconf' | cut -d ',' -f 5)
           curl -LsS -o sqlite.tar.gz https://sqlite.org/${TARBALL}
           VERIFY=$(openssl dgst -sha3-256 sqlite.tar.gz | cut -d ' ' -f 2)
-          if [ "$SHA3" != "$VERIFY" ]; then exit 1 ; fi
+          if [ "$SHA3" != "$VERIFY" ]; then
+            echo "::error::SQLite tarball checksum mismatch."
+            exit 1
+          fi
           tar -xzf sqlite.tar.gz && cd sqlite-autoconf-*
 
           CPPFLAGS="-DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_MAX_VARIABLE_NUMBER=250000 -DSQLITE_ENABLE_RTREE=1 -DSQLITE_ENABLE_GEOPOLY=1 -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_FTS3_PARENTHESIS=1 -DSQLITE_ENABLE_FTS5=1 -DSQLITE_ENABLE_STAT4=1 -DSQLITE_ENABLE_JSON1=1 -DSQLITE_SOUNDEX=1 -DSQLITE_ENABLE_MATH_FUNCTIONS=1 -DSQLITE_MAX_ATTACHED=125 -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 -DSQLITE_ENABLE_SNAPSHOT=1" ./configure --enable-shared=no
           make -j2 && sudo make install -j2
 
-      - if: matrix.sqlcipher == 1
-        name: Build SQLCipher
-        run: |
-          sudo apt install libssl-dev tcl
-          git clone https://github.com/sqlcipher/sqlcipher && cd sqlcipher && git checkout v4.6.1
-          ./configure --enable-tempstore=yes --with-crypto-lib=openssl --enable-load-extension --disable-tcl CFLAGS="-DSQLCIPHER_CRYPTO_OPENSSL -DSQLITE_ENABLE_COLUMN_METADATA -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS -DSQLITE_ENABLE_FTS5 -DSQLITE_ENABLE_GEOPOLY -DSQLITE_ENABLE_JSON1 -DSQLITE_ENABLE_MEMORY_MANAGEMENT=1 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_SNAPSHOT=1 -DSQLITE_ENABLE_STAT4 -DSQLITE_HAS_CODEC -DSQLITE_SOUNDEX"
-          make -j2 && sudo make install -j2
-
       - name: Configure build
         run: |
-          mkdir appbuild && mkdir appdir && cd appbuild
-          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=../appdir/usr -Wno-dev -DFORCE_INTERNAL_QSCINTILLA=ON -Dsqlcipher=${{ matrix.sqlcipher }} ..
+          mkdir -v appbuild appdir && cd appbuild
+          cmake -G Ninja \
+                -DCMAKE_BUILD_TYPE=Release \
+                -DCMAKE_INSTALL_PREFIX:PATH=../appdir/usr \
+                -DENABLE_TESTING=ON \
+                -DFORCE_INTERNAL_QSCINTILLA=ON \
+                -Dsqlcipher=${{ matrix.bundle == 'SQLCipher' }} ..
 
       - name: Build
         working-directory: ./appbuild
-        run: make install -j2
+        run: ninja install
+
+      - name: Tests
+        working-directory: ./appbuild
+        run: ninja test
 
       - name: Build AppImage
         run: |
@@ -74,15 +86,24 @@ jobs:
       - name: Rename a file
         run: |
           for i in DB_Browser_for_SQLite*; do mv "$i" "${i//_/.}"; done
-          if [ "${{ matrix.sqlcipher }}" = "1" ]; then
+          if [ "${{ matrix.bundle }}" = "SQLCipher" ]; then
             export FILE=$(ls DB.Browser.for.SQLite*.AppImage)
             export FILE=${FILE/SQLite/SQLCipher}
-            mv DB.Browser.for.SQLite*.AppImage $FILE
+            mv -v DB.Browser.for.SQLite*.AppImage $FILE
           fi
 
-      - name: Upload artifacts
+      - if: github.event_name != 'pull_request' && github.workflow != 'Build (Ubuntu)'
+        name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: build-artifacts-${{ matrix.os }}-${{ matrix.sqlcipher }}
+          name: build-artifacts-${{ matrix.os }}-${{ matrix.bundle }}
           path: DB.Browser.for.*.AppImage
           retention-days: 1
+
+      - if: github.event_name == 'workflow_dispatch' && github.workflow == 'Build (Ubuntu)'
+        name: Release
+        uses: softprops/action-gh-release@v2
+        with:
+          files: DB.Browser.for.*.AppImage
+          prerelease: true
+          tag_name: ${{ github.sha }}-ubuntu
